### ISSUE TITLE
Remove unnecessary try block?

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#108]
I realize I am probably at fault for this originally, but now knowing a tiny bit more I cannot think of any good reason for the nested try/finally block.

https://github.com/plus3it/watchmaker/blob/develop/src/watchmaker/managers/base.py#L239-L246

**Comment by KevinPlus3** [comment]
Yeah. I mean it's not crazy to do such things, but probably would be better to not have nested try/finally blocks.

**Comment by lorengordon** [comment]
Realized that the nested try block is protecting the finally block from failing if the opener fails to open the archive. Implementation is fine. Closing issue.
