### ISSUE TITLE
Publish SCAP scan with watchmaker releases

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#1089]
Idea is that SCAP scans would be hosted in the the s3 bucket, viewable through a CDN direct link, and linked from the GitHub release page. URLs something like:

* https://watchmaker.cloudarmor.io/releases/<version>/scans/<scan>

Might need to rename the scan files to something more user friendly than the current name. Could be done by renaming when pushing to s3, or by re-jiggering the file names in the scap-formula.

**Comment by YakDriver** [comment]
Closing based on plus3it/terrafirm#69
