### ISSUE TITLE
Mapping of log levels?

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#109]
Every time I see [this code](https://github.com/plus3it/watchmaker/blob/develop/src/watchmaker/logger/__init__.py#L16-L21) I want to refactor it to a mapping of some kind to eliminate the if statement, but I'm always in the middle of some other work where it would not be appropriate to make this change. Opening an issue to remember to address it later.

**Comment by KevinPlus3** [comment]
Thumbs up to move it to a mapping to reduce all those lines to one or two lines.
