### ISSUE TITLE
Config.yaml not updated with v0.18.0 release

### ISSUE THREAD

**Issue by crypticism** [plus3it/watchmaker#1179]
The static config.yaml file here:
* https://github.com/plus3it/watchmaker/blob/master/src/watchmaker/static/config.yaml

still references v0.17.0

**Comment by lorengordon** [comment]
Appreciate that. Patching here: https://github.com/plus3it/watchmaker/pull/1180

**Comment by lorengordon** [comment]
@crypticism Fix was just released in 0.18.1. The build system will tag it and push it to pypi shortly...
