### ISSUE TITLE
Default to the new yum repos for salt

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#119]
- https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-el6.repo
- https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-el7.repo
- https://s3.amazonaws.com/systemprep-repo/linux/saltstack/salt/yum.repos/salt-reposync-amzn.repo

**Comment by deonbah** [comment]
Hello, these repositories seem to be denied access to public when trying to run watchmaker after the installation process as noted by permission denied errors.

**Comment by lorengordon** [comment]
this is a closed, 3-year old issue. please open a new issue explaining what you're trying to do, what you expect to happen, and exactly what errors you are getting.
