### ISSUE TITLE
Watchmaker fails to join AWS AD Domain with EC2/Windows

### ISSUE THREAD

**Issue by jlongo62** [plus3it/watchmaker#1481]
I am using Watchmaker (https://watchmaker.readthedocs.io/en/stable/usage.html#watchmaker-as-ec2-userdata) to harden an AWS EC2 instance and Join a AWS AD domain. I have the following UserData block to accomplish this:

    <powershell>
       
    #Fix DNS Server to See Domain
        $adapters = Get-NetAdapter
        foreach ($adapter in $adapters)
        {
            Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses ("10.31.30.173", "10.31.31.22")
        }
        Get-DnsClientServerAddress
     
    #Apply Watchmaker
    # https://watchmaker.readthedocs.io/en/stable/usage.html#watchmaker-as-ec2-userdata
        $BootstrapUrl = "https://raw.githubusercontent.com/plus3it/watchmaker/master/docs/files/bootstrap/watchmaker-bootstrap.ps1"
        $PythonUrl = "https://www.python.org/ftp/python/3.6.8/python-3.6.8-amd64.exe"
        $PypiUrl = "https://pypi.org/simple"
        $YAMLConfig = "s3://dicelab-watchmaker/config.yaml"
        $LogDirectory = "C:\Watchmaker\Logs"
    
        # Download bootstrap file
        $BootstrapFile = "${Env:Temp}\$(${BootstrapUrl}.split('/')[-1])"
        (New-Object System.Net.WebClient).DownloadFile("$BootstrapUrl", "$BootstrapFile")
    
        # Install python
        & "$BootstrapFile" -PythonUrl "$PythonUrl" -Verbose -ErrorAction Stop
    
        # Install Watchmaker
        python -m pip install --index-url="$PypiUrl" --upgrade pip setuptools
        pip install --index-url="$PypiUrl" --upgrade watchmaker
    
        # Run Watchmaker
        watchmaker --log-level debug --log-dir=C:\Watchmaker\Logs --admin-users .\xadministrator:touchworks\admin --computer-name "MyNewName" --env T1 --ou-path "OU=Computers,OU=touchworks,DC=touchworks,DC=T1" 
    
    </powershell>

The AD Join fails to happen. What am I doing wrong ?

**Comment by lorengordon** [comment]
@jlongo62 I see your userdata referring to the dicelab domain. Please open a ticket with help@dicelab.net or https://help.dicelab.net. Such references are not appropriate for the public GitHub project.
