### ISSUE TITLE
Update the usage doc with a section on the azure equivalent of ec2 userdata

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#171]

**Comment by KevinPlus3** [comment]
Since I work with Azure environment now, I'll see if I can get this updated with the relevant info.

**Comment by ferricoxide** [comment]
@KevinPlus3
Fortunately, Azure supports usage of [cloud-init](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/using-cloud-init). So, shouldn't be _too_ much in the deltas.

**Comment by KevinPlus3** [comment]
Unfortunately, according to that page you linked, it is available for UnbuntuLTS or CoreOS Azure images.  No guaranties on the other images.  But nevertheless, our documentation could say something to the affect of "Make sure you Azure Linux image has cloud-init installed ..."

**Comment by ferricoxide** [comment]
Presumably we'd be opting to use the Azure-equivalent of the CBT AMI (which explicitly includes cloud-init). I _believe_ @ewierschke  was working with Loren on extending spel to produce Azure templates? If so, might update the documentation to link to the search-name for "our" template. Something like "Make sure your Azure Linux template has cloud-init installed - a known-good template can be found using..."?

**Comment by KevinPlus3** [comment]
Yep. @ewierschke sent me a link to his ARM templates - we could migrate his templates over to somewhere in watchmaker and then update the documentation per your suggestion.

**Comment by ferricoxide** [comment]
And, once they're validated good/equivalent, update the monthly AMI/template task to include "generate templates for Azure". =)

**Comment by KevinPlus3** [comment]
LOL Awesome.

**Comment by lorengordon** [comment]
Closed by https://github.com/plus3it/watchmaker/pull/464
