### ISSUE TITLE
Support installing config.yaml from a URL

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#2]

**Comment by marioncobretti** [comment]
Suggestion:
--config-file
Accepts local, or http(s) url
Validates that it exists
Validates that it is yaml
If Validation fails, should it just WARN and continue with default?  or should it halt and return that it doesnt exist or validate?

**Comment by lorengordon** [comment]
i vote for halt. if the user passes a value and it's bad, we should tell them it's bad so they can fix it, rather than maybe continuing to reference defaults they were trying to override.

**Comment by MarionTheBull** [comment]
Merged and resolved with PR #48
