### ISSUE TITLE
Start Incorporating Tests

### ISSUE THREAD

**Issue by KevinPlus3** [plus3it/watchmaker#321]
We may need to start the process of expanding Watchmaker to include tests, similar in vein to what Salt does, so we can start testing the results and errors we may expect from Watchmaker.  This will help to improve our review/approval process.

**Comment by KevinPlus3** [comment]
Added logger tests in #333.

**Comment by lorengordon** [comment]
Might want to switch from pytest-capturelog to [pytest-catchlog](https://pypi.python.org/pypi/pytest-catchlog). pytest-capturelog hasn't been updated in a good long while and does not appear to really support py3. pytest-catchlog is still active, and (skimming the issues) seems to have support for merging into pytest-core...

**Comment by KevinPlus3** [comment]
Cool. Will do once I get back to adding more tests ...
