### ISSUE TITLE
Watchmaker not setting the correct salt grain for Windows role (DC vs MS)

### ISSUE THREAD

**Issue by ewierschke** [plus3it/watchmaker#331]
When attempting to run watchmaker with the extra parameter for a Windows Domain Controller; `watchmaker --log-level debug --log-dir=C:\Watchmaker\Logs --ash-role DomainController`
Watchmaker does not appear to be setting the correct grain for ash-windows to apply the DomainController settings.

The ash-windows formula appears to be looking for the grain `ash-windows:lookup:role`, but watchmaker is setting the grain `ash-windows:role`

https://github.com/plus3it/ash-windows-formula/blob/master/ash-windows/map.jinja#L53-L56

https://github.com/plus3it/watchmaker/blob/develop/src/watchmaker/workers/salt.py#L729-L731

After promotion of the DC and execution of the above watchmaker run, salt_call.debug.log shows multiple references to the _MS files rather than the _DC files that should be applied to a Domain Controller.

**Comment by KevinPlus3** [comment]
Do we want this addressed in Watchmaker or in the formula?

**Comment by KevinPlus3** [comment]
Erik has informed me that the change should occur in Watchmaker.
