### ISSUE TITLE
Deployments to testpypi.python.org are failing

### ISSUE THREAD

**Issue by JonathonReinhart** [plus3it/watchmaker#337]
I noticed this because I was looking into the way you deploy (on `develop`) to `testpypi`. I see that [Job 1064](https://travis-ci.org/plus3it/watchmaker/jobs/248048787) failed to deploy:

> HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html) for url: https://testpypi.python.org/pypi

This seems like a Travis bug, in how they automatically handle `provider: pypi`.

**Comment by lorengordon** [comment]
@JonathonReinhart thanks for the heads up. Need to check if there's a way to send notifications on deploy failures. :shame:

Skimming the links in the error message, might be able to change the url in `.travis.yml` to `https://test.pypi.org/legacy`. Will test that tomorrow.

**Comment by lorengordon** [comment]
Yep, that worked. Fixed in #338. See https://travis-ci.org/plus3it/watchmaker/jobs/248425924. Thanks again!

**Comment by JonathonReinhart** [comment]
No problem. I'll be replicating your changes on my own projects, so thank you for figuring it out!
