### ISSUE TITLE
Manage selinux state

### ISSUE THREAD

**Issue by KevinPlus3** [plus3it/watchmaker#341]
As caught per Tom, "executing watchmaker via init script (userdata or otherwise) needs to be done with `setenforce 0` being executed first (just like firewall-cmd)", especially for EL7 and running Watchmaker via UserData.

**Comment by lorengordon** [comment]
Modified title to reflect better understanding of the issue. Proposed fix is to manage the selinux state within the SaltLinux worker, similar to how the salt-minion service is managed.
