### ISSUE TITLE
Include salt formulas with watchmaker package

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#42]
Use git submodules to pull salt formulas into `src/static` and include them with the watchmaker package. Update config file and/or `src/workers/salt.py` to reference the relative location in `static/` rather than downloading them over http/s.

**Comment by MarionTheBull** [comment]
Are we removing the ability to use formulas defined in the config.yaml? 
Are there instances were users may want to define a formula we dont package?

If we do not remove the config.yaml params, should the static copies override the versions defined in the config.yaml when there is a conflict?

**Comment by lorengordon** [comment]
How about making the config.yaml option more of an `extra_formulas` option. Always install the static formulas, and also install formulas specified in config.yaml. Formulas in config.yaml override static formulas, if there are dups.

**Comment by lorengordon** [comment]
Done in #54
