### ISSUE TITLE
FAQ Addition: `pip` Failures Under FIPS-Enabled Targets

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/watchmaker#432]
May want to move this from the notes section to the FAQ (and back-link) or otherwise include the data in the FAQ. People often miss things like notes that they might not miss if it's in an FAQ.

**Comment by ferrx** [comment]
I'm assuming you're talking about the watchmaker installation via pip within an instance that has FIPS enabled.

It's mentioned here http://watchmaker.readthedocs.io/en/stable/usage.html#linux

but not here http://watchmaker.readthedocs.io/en/stable/installation.html which is where I would assume to see it. When installing, this page was the first place I looked for instructions.

**Comment by ferricoxide** [comment]
Yeah. We're looking to enhance the documentation, in general, with some stuff either moving to the FAQ and being back-linked to other sections that want the pointer.

Were the documentation tools leveraging other than Markdown, it would be a bit easier to include tooltip-style notation and/or other types of text-block re-use.
