### ISSUE TITLE
pytest-capturelog is blacklisted, switch to pytest-catchlog

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#443]
See https://github.com/pytest-dev/pytest/pull/3005.

pytest-catchlog: https://github.com/eisensheng/pytest-catchlog

**Comment by KevinPlus3** [comment]
Adding note here - while we have merged in this change - it appears the test is failing for the newer version of pytest that we will hopefully be moving to.  So I am going to look into updating the tests so the new version of pytest can be used.

**Comment by KevinPlus3** [comment]
Conditional added to test.txt in requirements to use older version for Python 2.6 and Python 3.3 and use newer version for 2.7 and 3.4+.

Updated test_logger since pytest 3.3 now captures logging.
