### ISSUE TITLE
Link references broken for certain heading anchor links in Watchmaker's Readthedocs website

### ISSUE THREAD

**Issue by eemperor** [plus3it/watchmaker#468]
Certain heading anchor links in html generated for [Watchmaker Readthedocs](https://watchmaker.readthedocs.io/en/stable/index.html) do not have the heading name but instead is given an arbitrary `id<#>` name.

https://watchmaker.readthedocs.io/en/stable/configuration.html#id1
https://watchmaker.readthedocs.io/en/stable/configuration.html#id2
https://watchmaker.readthedocs.io/en/stable/contributing.html#id1

This causes link references to the heading to not work properly.

**Comment by lorengordon** [comment]
Closed by https://github.com/plus3it/watchmaker/pull/469
