### ISSUE TITLE
Use sha as build number in dev pkgs, instead of CI build number

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#619]
We've been pushing dev pkgs to testpypi using travis for quite a while, but we recently also added standalone binaries that are pushed to an S3 bucket. Those packages need to be created on a like platform (i.e. a Windows pkg needs to be created on a Windows system). So now we have appveyor building Windows standalone pkgs and travis building Linux standalone pkgs.

The build version ends up the same, despite being built in two different places, because we aren't actually setting the build version in the CI jobs for these standalone pkgs.

* https://github.com/plus3it/watchmaker/blob/develop/.travis.yml#L88
* https://github.com/plus3it/watchmaker/blob/develop/appveyor.yml#L61

This leads to a discrepancy between the testpypi dev version and the standalone dev version.

We can align the two by using the sha of the built commit as the build number, for all dev deploys, i.e. `x.x.x.dev<sha>`.

**Comment by YakDriver** [comment]
Fixed in PR #621
