### ISSUE TITLE
Install salt formulas distributed with the watchmaker package by default

### ISSUE THREAD

**Issue by lorengordon** [plus3it/watchmaker#68]
Currently, salt formulas are specified in config.yaml, and downloaded and unzipped. 

The default set of salt formulas have been added as submodules so they are packaged with watchmaker, so they should be installed from the local copy by default, instead of downloading and unzipping them.

The download and unzip option can be preserved as a way for the user to pull in other salt formulas (or write over the packaged one). This piece could also be worked in a separate issue.

**Comment by KevinPlus3** [comment]
Should be addressed with PR #83. Need to remember that if you use python setup.py install to install Watchmaker, be sure you have the submodules cloned to the static/salt directory.  This is done by running 'git submodule update --init --recursive' before setup.py installation.

**Comment by lorengordon** [comment]
Added some notes to the docs in #86 about pulling in the submodules.
