### ISSUE TITLE
Disable salt-minion service on Linux hosts

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/watchmaker#72]
By default, Watchmaker's installation of the salt packages installs the `salt-minion` service. This service should be stopped and disabled:
- EL6: `chkconfig salt-minion off ; service salt-minion stop`
- EL7: `systemctl stop salt-minion ; systemctl disable salt-minion ; systemctl mask salt-minion`

**Comment by lorengordon** [comment]
@ferricoxide can you test if we can use salt itself to properly stop and disable the salt-minion on EL6 and EL7, rather than the platform-specific calls? That way we don't need logic to handle different platforms...

`salt-call --local service.stop salt-minion && salt-call --local service.disable salt-minion`

**Comment by ferricoxide** [comment]
Just for clarity: is the above testing with an eye towards adding a standardized salt-state to the deployed state sets or something to be run as a stand-alone part of UserData? If the latter, is there a specific value to using this method versus generically-prescribing "shut off the salt-minion service at launch time"?

**Comment by lorengordon** [comment]
We would incorporate that into watchmaker, just after the install step and (probably) before running the highstate. We already have logic to run salt commands, such as setting grains and applying states, so this is just extending that logic to run one more salt command.

**Comment by ferricoxide** [comment]
Cool. I'll try to give it a quick-check, this morning.

**Comment by KevinPlus3** [comment]
Any success on these salt commands ... I am just reading this and realizing I could wrap this into the current PR.

**Comment by lorengordon** [comment]
Ahh, no, that PR is large enough. Prefer keeping PRs small and focused on a single issue so they are easier to review.

**Comment by lorengordon** [comment]
Thinking about this more, we should test prior to salt install if salt is already present/enabled/running and preserve that state. Starting to see people using salt for their own purposes, and would prefer to avoid stepping on their toes...
