### ISSUE TITLE
The AllowGroup Token-Processing for the sshd_config File May Not be Idempotent

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/watchmaker#823]
If one runs watchmaker more than once - specifying the `-A` option each time (to, say, correct the list of groups), the `/etc/sshd_config` file's `AllowGroup` list is continually appended rather than overwritten.

**After Initial Run**
~~~
# watchmaker -e dev --no-reboot -A builder,domain^users -t <HOSTNAME> --log-dir=/var/log/watchmaker -c s3://dicelab-watchmaker/config.yaml
# grep ^AllowGroups /etc/ssh/sshd_config
AllowGroups  maintuser builder,domain
~~~

**After Second Run**
~~~
# watchmaker -e dev --no-reboot -A "builder domain^users" -t <HOSTNAME> --log-dir=/var/log/watchmaker -c s3://dicelab-watchmaker/config.yaml
# grep ^AllowGroups /etc/ssh/sshd_config
AllowGroups  maintuser builder,domain^users builder^domain^users
~~~

Obviously, the above may be a result of `watchmaker` not parsing the first run's comma-delimited argument and the second'run's space-delimited argument as two values (each) – such that it can't properly identify an "already exists" condition.

Potentially tie-in to #822

**Comment by lorengordon** [comment]
It is idempotent in the sense that if the group specified by the user is already in the list, the user will not be added a second time. But, it is not aware of what the user may have added to the list _outside_ of watchmaker, nor is it aware of its own prior executions or the values used previously. There isn't a way of knowing this, within the design of the utility.
