### ISSUE TITLE
Documentation for cloud formation scripts point to terraform scripts

### ISSUE THREAD

**Issue by bedaronco** [plus3it/watchmaker#868]
When viewing the documentation at https://watchmaker.readthedocs.io/en/stable/usage.html#watchmaker-as-a-cloudformation-template, the links under the CloudFormation Templates point to the Terraform templates.  They should probably link to here instead:  https://github.com/plus3it/terraform-aws-watchmaker/blob/master/modules/lx-autoscale/watchmaker-lx-autoscale.template.cfn.yaml

**Comment by YakDriver** [comment]
This appears to be fixed as the links now take you to the subdirectory rather than the file. Thanks for your input and let us know if you still see any issue.

**Comment by YakDriver** [comment]
As I believe the issue is fixed and I haven't heard any complaints, I'm going to close this. Please open a new issue if there continues to be a problem! Thanks for your help.
