### ISSUE TITLE
Incorporate Salt bootstrap installation for Windows.

### ISSUE THREAD

**Issue by KevinPlus3** [plus3it/watchmaker#90]
Currently, we can install Salt via Linux using Salt's bootstrap script (sh) and pass in the Salt Git repo url and a version.  We should update SaltWindows to be able to install Salt in the same manner using Salt's bootstrap Powershell script.

We may want to look into expanding the parameters allowed for for the bootstrap scripts for both OSes to include other bootstrap params: see https://github.com/saltstack/salt-bootstrap.

**Comment by KevinPlus3** [comment]
Apparently, the current ps1 script just installs via the executable installer that is packaged for Windows. So it is not similar to the sh script.  This is very low-priority and can be re-explored later.

**Comment by lorengordon** [comment]
No longer necessary with the new cli, and the new ps1 bootstrapper.
