### ISSUE TITLE
world inaccessible error /etc/systemd/system/tmp.mount.d/options.conf

### ISSUE THREAD

**Issue by ssmoquin** [plus3it/watchmaker#937]
Get the following warning message in log file repeatedly:

Configuration file /etc/systemd/system/tmp.mount.d/options.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.

Found the script /srv/watchmaker/salt/formulas/ash-linux-formula/ash-linux/el7/VendorSTIG/cat3/mount_options_tmp.sls is setting the mode of the file to 0600. 

Need to modify the mode to 644.

**Comment by ferricoxide** [comment]
Fixed in [sub-project](https://github.com/plus3it/ash-linux-formula/issues/280)
