### ISSUE TITLE
Update readthedocs Contents

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/watchmaker#96]
No point having a reference to watchmaker.readthedocs.io in the README.md if the docs hosted there are not kept up-to-date.

Marking as "bug" even though this is likely more a process issue rather than a software bug, per se.

**Comment by lorengordon** [comment]
This is done automatically upon a tagged release.

**Comment by ferricoxide** [comment]
K... Why are the docs that get installed via `mkdocs` different from the ones on readthedocs when they're in the same branch? Something _seems_ out of sync with that.

**Comment by lorengordon** [comment]
readthedocs does not use `mkdocs`; it uses `sphinx`. I do not believe the instructions `mkdocs` are currently valid.

**Comment by lorengordon** [comment]
Hmm, readthedocs is actually still using `mkdocs`. And when I serve mkdocs locally, the content is exactly the same as what is in the [develop branch on readthedocs](http://watchmaker.readthedocs.io/en/develop/). So, I can't replicate what you are saying without a better description of the steps you followed to get there.

**Comment by ferricoxide** [comment]
contents from watchmaker.readthedocs.io:

![image](https://cloud.githubusercontent.com/assets/7087031/21409921/3c4e85ee-c7ab-11e6-8820-a9daab3eff59.png)

contents from `mkdocs`:

![image](https://cloud.githubusercontent.com/assets/7087031/21409951/71121804-c7ab-11e6-9ecb-31df7e6bb4a0.png)

**Comment by lorengordon** [comment]
That is `latest` not `develop`. `latest` tracks the master branch. `develop` follows develop. Follow the link I provided and you'll see the same content.

**Comment by ferricoxide** [comment]
`mkdocs`:

![image](https://cloud.githubusercontent.com/assets/7087031/21410098/44cd0064-c7ac-11e6-84fb-8dc33b706928.png)

There is no "latest" and "develop" is the default branch.

**Comment by lorengordon** [comment]
Are you following the link? `latest` is readthedocs terminology. It exists there, not in git.

**Comment by ferricoxide** [comment]
Was following the link displayed on the GitHub page.

No kind of `%branch%` token that can be placed in the link-target (so that you get taken to the approriate URL based on the branch being viewed)?

**Comment by lorengordon** [comment]
/shrug. it's mostly only an issue _now_ because we don't have a release, so the master branch docs correspond to what is for all intents and purposes just a random spot in the git history where the docs are completely irrelevant. once we tag a release, the default on readthedocs will correspond to the current release in pypi, which will need to be something meaningful for the release to mean anything. If we want to link to both the current release docs and the develop docs, we can put both links in the readme.

**Comment by ferricoxide** [comment]
No biggie. Would also be handy if readthedocs offered a referrer-link parsing-method for determining which doc-version to do on-the-fly URL-rewriting on. :-p

Any way, "never mind". Next time I'll try to remember to look at the redirected URL and hand-editing as necessary.
